/**
 * Auto-generated TypeScript types from Pydantic models.
 * Generated by: python scripts/generate_types.py
 * DO NOT EDIT MANUALLY — regenerate instead.
 */

export interface BacktestConfigGenerated {
  strategy?: string;
  symbol?: string;
  start_date?: string;
  end_date?: string;
  initial_balance?: number;
  contract_size?: number;
  leverage?: number;
  pip_size?: number;
  swap_long?: number;
  swap_short?: number;
  tick_file_path?: string | null;
  commission_per_lot?: number;
  commission_model?: string;
  strategy_params?: Record<string, unknown>;
  max_equity_samples?: number;
  verbose?: boolean;
}

export interface BacktestResultGenerated {
  status: string;
  symbol?: string;
  strategy?: string;
  start_date?: string;
  end_date?: string;
  initial_balance?: number;
  final_balance?: number;
  total_pnl?: number;
  return_percent?: number;
  total_trades?: number;
  total_trades_opened?: number;
  winning_trades?: number;
  losing_trades?: number;
  win_rate?: number;
  average_win?: number;
  average_loss?: number;
  largest_win?: number;
  largest_loss?: number;
  max_drawdown?: number;
  max_drawdown_pct?: number;
  sharpe_ratio?: number;
  sortino_ratio?: number;
  profit_factor?: number;
  recovery_factor?: number;
  total_swap?: number;
  peak_equity?: number;
  peak_balance?: number;
  max_open_positions?: number;
  max_used_margin?: number;
  stop_out_occurred?: boolean;
  equity_curve?: number[];
  equity_timestamps?: string[];
  equity_curve_sampled?: boolean;
  equity_curve_original_size?: number;
  trades?: Record<string, unknown>[];
  trades_total?: number;
  trades_truncated?: boolean;
  broker_settings?: Record<string, number> | null;
  message?: string | null;
  error_info?: Record<string, unknown> | null;
}

export interface TradeRecordGenerated {
  id: number;
  direction: string;
  entry_price: number;
  exit_price: number;
  entry_time: string;
  exit_time: string;
  lot_size: number;
  profit_loss: number;
  commission?: number;
  exit_reason?: string;
}

export interface SweepConfigGenerated {
  strategy?: string;
  symbol?: string;
  start_date?: string;
  end_date?: string;
  initial_balance?: number;
  contract_size?: number;
  leverage?: number;
  pip_size?: number;
  swap_long?: number;
  swap_short?: number;
  tick_file_path?: string | null;
  sweep_type?: string;
  num_combinations?: number;
  parameter_ranges?: unknown[];
}

export interface SweepProgressGenerated {
  sweep_id: string;
  status: string;
  completed?: number;
  total?: number;
  percent?: number;
  current_result?: Record<string, unknown> | null;
  best_so_far?: Record<string, unknown> | null;
  message?: string | null;
}

export interface SweepResultEntryGenerated {
  parameters: Record<string, unknown>;
  final_balance?: number;
  return_percent?: number;
  sharpe_ratio?: number;
  max_drawdown?: number;
  profit_factor?: number;
  win_rate?: number;
  total_trades?: number;
  sortino_ratio?: number;
  recovery_factor?: number;
  max_open_positions?: number;
  stop_out?: boolean;
}

export interface ParameterRangeGenerated {
  name: string;
  min: number;
  max: number;
  step?: number;
}


