"""
Generate TypeScript interfaces from Pydantic models.
Run: python scripts/generate_types.py > dashboard/src/types/generated.ts
"""

import json
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from api.models.backtest import BacktestConfig, BacktestResult, TradeRecord
from api.models.sweep import SweepConfig, SweepProgress, SweepResultEntry, ParameterRange
from api.models.broker import BrokerConnectRequest


def pydantic_to_ts(model_class, interface_name=None):
    """Convert a Pydantic model to a TypeScript interface."""
    name = interface_name or model_class.__name__
    schema = model_class.model_json_schema()
    lines = [f"export interface {name} {{"]

    properties = schema.get("properties", {})
    required = set(schema.get("required", []))

    for prop_name, prop_info in properties.items():
        ts_type = json_schema_to_ts(prop_info)
        optional = "?" if prop_name not in required else ""
        # Add description as comment
        desc = prop_info.get("description", "")
        if desc:
            lines.append(f"  /** {desc} */")
        lines.append(f"  {prop_name}{optional}: {ts_type};")

    lines.append("}")
    return "\n".join(lines)


def json_schema_to_ts(schema):
    """Convert JSON schema type to TypeScript type."""
    if not isinstance(schema, dict):
        return "unknown"
    if "anyOf" in schema:
        types = [json_schema_to_ts(s) for s in schema["anyOf"] if s.get("type") != "null"]
        null = any(s.get("type") == "null" for s in schema["anyOf"])
        ts = " | ".join(types) if types else "unknown"
        if null:
            ts += " | null"
        return ts

    schema_type = schema.get("type", "unknown")

    if schema_type == "string":
        if "enum" in schema:
            return " | ".join(f'"{v}"' for v in schema["enum"])
        return "string"
    elif schema_type == "number" or schema_type == "integer":
        return "number"
    elif schema_type == "boolean":
        return "boolean"
    elif schema_type == "array":
        items = schema.get("items", {})
        item_type = json_schema_to_ts(items)
        return f"{item_type}[]"
    elif schema_type == "object":
        additional = schema.get("additionalProperties")
        if additional:
            val_type = json_schema_to_ts(additional)
            return f"Record<string, {val_type}>"
        return "Record<string, unknown>"
    elif schema_type == "null":
        return "null"
    else:
        return "unknown"


def main():
    header = """/**
 * Auto-generated TypeScript types from Pydantic models.
 * Generated by: python scripts/generate_types.py
 * DO NOT EDIT MANUALLY — regenerate instead.
 */

"""
    output = header

    models = [
        (BacktestConfig, "BacktestConfigGenerated"),
        (BacktestResult, "BacktestResultGenerated"),
        (TradeRecord, "TradeRecordGenerated"),
        (SweepConfig, "SweepConfigGenerated"),
        (SweepProgress, "SweepProgressGenerated"),
        (SweepResultEntry, "SweepResultEntryGenerated"),
        (ParameterRange, "ParameterRangeGenerated"),
    ]

    for model, name in models:
        output += pydantic_to_ts(model, name) + "\n\n"

    print(output)


if __name__ == "__main__":
    main()
